<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VNTextPatchInstaller</AssemblyName>
    <RootNamespace>VNText.PatchInstaller</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
  </ItemGroup>
</Project>
