"""Fail-closed native Ren'Py overlay writer for proven loose-source locators."""
from __future__ import annotations

import ast
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile

from vntext.patch_gate import load_review_only_keys, patch_skip_reason
from vntext.package_io import read_translation_rows
from vntext.patchability import validate_renpy_contract


class RenPyPatchError(ValueError):
    pass


_STRING_BLOCK = re.compile(
    r"^(?P<indent>[ \t]*)translate\s+(?P<language>[A-Za-z_]\w*)\s+strings\s*:(?:\s*#.*)?$"
)
_STRING_STATEMENT = re.compile(r'^(?P<key>old|new)\s+(?P<quote>"(?:\\.|[^"\\])*")\s*$')
_COMPILED_TO_SOURCE_SUFFIX = {".rpyc": ".rpy", ".rpymc": ".rpym"}


def _quote(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def _source_present(script: str, source: str) -> bool:
    """Check literal, escaped, or whitespace-folded native source text."""
    if source in script or _quote(source) in script:
        return True
    folded_source = re.sub(r"\s+", " ", source).strip()
    if not folded_source:
        return False
    return folded_source in re.sub(r"\s+", " ", script)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _inventory_target_language_mappings(
    root: Path,
    language: str,
) -> tuple[dict[tuple[str, str], dict[str, object]], dict[Path, str]]:
    """Inventory source-backed mappings before allowing an overlay write."""

    target_root = root / "game" / "tl" / language
    if not target_root.is_dir():
        return {}, {}

    compiled_only: list[tuple[Path, Path]] = []
    source_paths: list[Path] = []
    for path in sorted(
        (candidate for candidate in target_root.rglob("*") if candidate.is_file()),
        key=lambda candidate: candidate.relative_to(root).as_posix(),
    ):
        suffix = path.suffix.casefold()
        source_suffix = _COMPILED_TO_SOURCE_SUFFIX.get(suffix)
        if suffix in {".rpy", ".rpym"}:
            source_paths.append(path)
        elif source_suffix:
            source_path = path.with_suffix(source_suffix)
            if not source_path.is_file():
                compiled_only.append((path, source_path))

    if compiled_only:
        details = "; ".join(
            f"{compiled} (expected inspectable source {source})"
            for compiled, source in compiled_only
        )
        raise RenPyPatchError(
            "Ren'Py target-language mapping gate blocked: compiled-only .rpyc/.rpymc "
            "is unverifiable by the current source mapping inventory: "
            f"{details}. Provide the corresponding loose .rpy/.rpym source or rebuild "
            "the target translation artifacts from inspectable source, then retry; "
            "no overlay was written."
        )

    for path in source_paths:
        try:
            path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise RenPyPatchError(
                "Ren'Py target-language mapping source is unverifiable: "
                f"{path}: {exc}; no overlay was written."
            ) from exc

    return _read_existing_string_mappings(root, language)


def _render_overlay(dialogues: list[tuple[dict, str]], strings: dict[tuple[str, str], str]) -> str:
    payload = ["# Generated by VNText Studio. Do not edit native IDs.", ""]
    for entry, translation in dialogues:
        locator = entry["locator"]
        speaker = str(locator.get("speaker") or entry.get("object_info") or "")
        payload.extend(
            [
                f"translate vietnamese {locator['native_id']}:",
                f"    # {speaker + ' ' if speaker else ''}{_quote(str(entry['source_text']))}",
                f"    {speaker + ' ' if speaker else ''}{_quote(translation)}",
                "",
            ]
        )
    if strings:
        payload.extend(["translate vietnamese strings:"])
        for (_language, source), translation in sorted(strings.items()):
            payload.extend([f"    old {_quote(source)}", f"    new {_quote(translation)}"])
    return "\n".join(payload) + "\n"


def _render_activation() -> str:
    return 'init 999 python:\n    config.language = "vietnamese"\n'


def _validate_overlay_pair(target: Path, activation: Path) -> bool:
    target_exists = target.exists()
    activation_exists = activation.exists()
    if target_exists != activation_exists:
        raise RenPyPatchError(
            "Ren'Py overlay target pair is inconsistent: both vntext.rpy and "
            "zzz_vntext_vietnamese.rpy must exist or neither may exist"
        )
    if not target_exists:
        return False
    if not target.is_file() or not activation.is_file():
        raise RenPyPatchError(
            "Ren'Py overlay target pair is inconsistent: both targets must be regular files"
        )
    try:
        target.read_bytes()
        activation.read_bytes()
    except OSError as exc:
        raise RenPyPatchError(f"Ren'Py overlay target pair is unverifiable: {exc}") from exc
    return True


def _overlay_residual(target: Path, activation: Path, stage_root: Path | None) -> str:
    def state(path: Path) -> str:
        if not path.exists():
            return "missing"
        if path.is_file():
            return "file"
        return "non-file"

    staging = "missing" if stage_root is None or not stage_root.exists() else str(stage_root)
    return (
        f"target={state(target)} ({target}), activation={state(activation)} ({activation}), "
        f"staging={staging}"
    )


def _cleanup_overlay_stage(
    stage_root: Path | None,
    output: Path,
    output_was_present: bool,
    target: Path | None = None,
) -> None:
    if stage_root is not None and stage_root.exists():
        shutil.rmtree(stage_root)
    if target is not None:
        current = target.parent
        while current != output and current.exists():
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent
    if not output_was_present and output.is_dir() and not any(output.iterdir()):
        output.rmdir()


def _rollback_overlay_pair(
    target: Path,
    activation: Path,
    backup_target: Path,
    backup_activation: Path,
    *,
    had_pair: bool,
    commit_started: bool,
    published: set[Path],
) -> list[str]:
    errors: list[str] = []
    finals_to_remove: set[Path] = set(published)
    if had_pair:
        if backup_target.exists():
            finals_to_remove.add(target)
        if backup_activation.exists():
            finals_to_remove.add(activation)
    elif commit_started:
        finals_to_remove.update(path for path in (target, activation) if path.exists())

    for path in (target, activation):
        if path not in finals_to_remove or not path.exists():
            continue
        try:
            path.unlink()
        except OSError as exc:
            errors.append(f"remove {path}: {exc}")

    for backup, final in ((backup_target, target), (backup_activation, activation)):
        if not backup.exists():
            continue
        try:
            os.replace(str(backup), str(final))
        except OSError as exc:
            errors.append(f"restore {final}: {exc}")
    return errors


def _publish_overlay_pair(
    output: Path,
    target: Path,
    activation: Path,
    payload: str,
    activation_payload: str,
    existing_snapshots: dict[Path, str],
    source_snapshots: dict[Path, str],
) -> None:
    output_was_present = output.exists()
    if output_was_present and not output.is_dir():
        raise RenPyPatchError(f"Ren'Py patch output is not a directory: {output}")
    had_pair = _validate_overlay_pair(target, activation)
    stage_root: Path | None = None
    backup_target: Path | None = None
    backup_activation: Path | None = None
    published: set[Path] = set()
    commit_started = False

    try:
        output.mkdir(parents=True, exist_ok=True)
        stage_root = Path(tempfile.mkdtemp(prefix=".renpy-overlay-", dir=str(output)))
        stage_target = stage_root / "game" / "tl" / "vietnamese" / "vntext.rpy"
        stage_activation = stage_root / "game" / "zzz_vntext_vietnamese.rpy"
        stage_target.parent.mkdir(parents=True, exist_ok=True)
        stage_activation.parent.mkdir(parents=True, exist_ok=True)
        try:
            stage_target.write_text(payload, encoding="utf-8")
        except Exception as exc:  # noqa: BLE001 - transaction boundary reports the exact failure.
            raise RenPyPatchError(f"Ren'Py overlay staging write failed: {exc}") from exc
        try:
            stage_activation.write_text(activation_payload, encoding="utf-8")
        except Exception as exc:  # noqa: BLE001 - transaction boundary reports the exact failure.
            raise RenPyPatchError(f"Ren'Py activation staging write failed: {exc}") from exc
        try:
            staged_overlay = stage_target.read_text(encoding="utf-8")
            staged_activation = stage_activation.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise RenPyPatchError(f"Ren'Py overlay read-back failed during staging: {exc}") from exc
        if staged_overlay != payload:
            raise RenPyPatchError("Ren'Py overlay read-back failed during staging: overlay mismatch")
        if staged_activation != activation_payload:
            raise RenPyPatchError("Ren'Py overlay read-back failed during staging: activation mismatch")

        _verify_existing_snapshots(existing_snapshots)
        for source_path, expected_sha256 in source_snapshots.items():
            try:
                actual_sha256 = _sha256(source_path)
            except OSError as exc:
                raise RenPyPatchError(f"Ren'Py source read-back failed: {source_path}: {exc}") from exc
            if actual_sha256 != expected_sha256:
                raise RenPyPatchError(f"original Ren'Py source changed: {source_path}")

        backup_target = stage_root / ".previous-vntext.rpy"
        backup_activation = stage_root / ".previous-activation.rpy"
        target.parent.mkdir(parents=True, exist_ok=True)
        activation.parent.mkdir(parents=True, exist_ok=True)
        if had_pair:
            commit_started = True
            os.replace(str(target), str(backup_target))
            os.replace(str(activation), str(backup_activation))
        commit_started = True
        os.replace(str(stage_target), str(target))
        published.add(target)
        os.replace(str(stage_activation), str(activation))
        published.add(activation)

        reasons: list[str] = []
        try:
            rendered = target.read_text(encoding="utf-8")
            rendered_activation = activation.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            rendered = rendered_activation = ""
            reasons.append(f"overlay read-back failed: {exc}")
        if rendered != payload:
            reasons.append("overlay read-back mismatch")
        if rendered_activation != activation_payload:
            reasons.append("activation read-back mismatch")
        try:
            _verify_existing_snapshots(existing_snapshots)
        except RenPyPatchError as exc:
            reasons.append(str(exc))
        for source_path, expected_sha256 in source_snapshots.items():
            try:
                actual_sha256 = _sha256(source_path)
            except OSError as exc:
                reasons.append(f"source read-back failed: {source_path}: {exc}")
                continue
            if actual_sha256 != expected_sha256:
                reasons.append(f"original Ren'Py source changed: {source_path}")
        if reasons:
            raise RenPyPatchError("Ren'Py overlay read-back failed: " + "; ".join(reasons))

        _cleanup_overlay_stage(stage_root, output, output_was_present, target)
        stage_root = None
    except Exception as exc:  # noqa: BLE001 - fail-closed transaction boundary.
        rollback_errors: list[str] = []
        if commit_started and backup_target is not None and backup_activation is not None:
            rollback_errors = _rollback_overlay_pair(
                target,
                activation,
                backup_target,
                backup_activation,
                had_pair=had_pair,
                commit_started=commit_started,
                published=published,
            )
        cleanup_error = ""
        if not rollback_errors:
            try:
                _cleanup_overlay_stage(stage_root, output, output_was_present, target)
                stage_root = None
            except OSError as cleanup_exc:
                cleanup_error = f"staging cleanup failed: {cleanup_exc}"
        message = str(exc)
        if not isinstance(exc, RenPyPatchError):
            phase = "publish" if commit_started else "staging"
            message = f"Ren'Py overlay transaction failed during {phase}: {exc}"
        details: list[str] = []
        if rollback_errors:
            details.append("rollback failed: " + "; ".join(rollback_errors))
        if cleanup_error:
            details.append(cleanup_error)
        details.append("residual: " + _overlay_residual(target, activation, stage_root))
        raise RenPyPatchError(message + "; " + "; ".join(details)) from exc


def _read_existing_string_mappings(
    root: Path,
    language: str,
) -> tuple[dict[tuple[str, str], dict[str, object]], dict[Path, str]]:
    """Read exact target mappings already present in the game copy."""

    target_root = root / "game" / "tl" / language
    if not target_root.is_dir():
        return {}, {}
    mappings: dict[tuple[str, str], dict[str, object]] = {}
    snapshots: dict[Path, str] = {}
    paths = sorted(
        (
            path
            for path in target_root.rglob("*")
            if path.is_file() and path.suffix.casefold() in {".rpy", ".rpym"}
        ),
        key=lambda path: path.relative_to(root).as_posix(),
    )
    for path in paths:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as exc:
            raise RenPyPatchError(f"existing Ren'Py string mapping is unverifiable: {path}: {exc}") from exc
        index = 0
        while index < len(lines):
            block = _STRING_BLOCK.fullmatch(lines[index])
            if not block:
                index += 1
                continue
            block_language = block.group("language")
            end = index + 1
            while end < len(lines):
                candidate = lines[end]
                if not candidate[:1].isspace() and candidate.lstrip().startswith("translate "):
                    break
                end += 1
            if block_language == language:
                pending: tuple[str, int] | None = None
                for line_number in range(index + 1, end):
                    raw = lines[line_number]
                    value = raw.strip()
                    if not value or value.startswith("#"):
                        continue
                    if not raw[:1].isspace():
                        raise RenPyPatchError(
                            f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                        )
                    statement = _STRING_STATEMENT.fullmatch(value)
                    if not statement:
                        raise RenPyPatchError(
                            f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                        )
                    try:
                        text = ast.literal_eval(statement.group("quote"))
                    except (SyntaxError, ValueError) as exc:
                        raise RenPyPatchError(
                            f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                        ) from exc
                    if not isinstance(text, str):
                        raise RenPyPatchError(
                            f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                        )
                    key = statement.group("key")
                    if key == "old":
                        if pending is not None:
                            raise RenPyPatchError(
                                f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                            )
                        pending = (text, line_number + 1)
                    elif pending is None:
                        raise RenPyPatchError(
                            f"existing Ren'Py string mapping is unverifiable: {path}:{line_number + 1}"
                        )
                    else:
                        source, old_line = pending
                        identity = (language, source)
                        if identity in mappings:
                            prior = mappings[identity]
                            raise RenPyPatchError(
                                "existing Ren'Py string mapping is unverifiable: "
                                f"duplicate ({language!r}, {source!r}) at {path}:{old_line} "
                                f"and {prior['path']}:{prior['old_line']}"
                            )
                        mappings[identity] = {
                            "source": source,
                            "translation": text,
                            "path": str(path),
                            "old_line": old_line,
                            "new_line": line_number + 1,
                        }
                        pending = None
                if pending is not None:
                    raise RenPyPatchError(
                        f"existing Ren'Py string mapping is unverifiable: {path}:{pending[1]} has no new"
                    )
                snapshots[path] = _sha256(path)
            index = end
    return mappings, snapshots


def _verify_existing_snapshots(snapshots: dict[Path, str]) -> None:
    for path, expected in snapshots.items():
        try:
            actual = _sha256(path)
        except OSError as exc:
            raise RenPyPatchError(f"existing Ren'Py string mapping became unverifiable: {path}: {exc}") from exc
        if actual != expected:
            raise RenPyPatchError(f"existing Ren'Py string mapping changed during patch: {path}")


def _write_verification(
    output: Path,
    target: Path,
    entries: list[dict],
    ok: bool,
    reason: str = "",
    records: list[dict] | None = None,
    already_satisfied: int = 0,
) -> dict:
    results = records or [
        {
            "key": str(entry.get("key") or ""),
            "status": "PASS" if ok else "FAIL",
            "method": (
                "renpy_overlay_dialogue"
                if str(entry.get("import_method")) == "renpy_dialogue"
                else "renpy_overlay_string"
            ),
            "target": str(target),
        }
        for entry in entries
    ]
    if records:
        for result in results:
            result["status"] = "PASS" if ok else "FAIL"
    verification = {
        "status": "PASS" if ok else "FAIL",
        "counts": {"PASS": len(results) if ok else 0, "FAIL": 0 if ok else len(results)},
        "results": results,
        "already_satisfied": already_satisfied,
    }
    if reason:
        verification["reason"] = reason
    (output / "patch_verification.json").write_text(
        json.dumps(verification, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return verification


def _build_verification_records(
    entries: list[dict],
    dialogues: list[tuple[dict, str]],
    target: Path,
    already_satisfied: dict[tuple[str, str], dict[str, object]],
) -> tuple[list[dict], list[dict]]:
    verification_entries = [entry for entry, _translation in dialogues]
    verification_entries.extend(
        entry for entry in entries if str(entry.get("import_method")) == "renpy_string"
    )
    verification_records = []
    for entry in verification_entries:
        method = "renpy_overlay_dialogue" if str(entry.get("import_method")) == "renpy_dialogue" else "renpy_overlay_string"
        record = {
            "key": str(entry.get("key") or ""),
            "method": method,
            "target": str(target),
            "reason": "patched",
        }
        if method == "renpy_overlay_string":
            locator = entry.get("locator") if isinstance(entry.get("locator"), dict) else {}
            identity = ("vietnamese", str(locator.get("source") or ""))
            existing = already_satisfied.get(identity)
            if existing is not None:
                record["target"] = str(existing["path"])
                record["reason"] = "already_satisfied"
                record["existing_mapping"] = {
                    "old_line": existing["old_line"],
                    "new_line": existing["new_line"],
                }
        verification_records.append(record)
    return verification_entries, verification_records


def apply_renpy_translation_package(csv_path: str, manifest_path: str, game_root: str, output_dir: str, progress_callback=None) -> list[str]:
    rows = read_translation_rows(csv_path)
    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8-sig"))
    entries = [item for item in manifest.get("entries", []) if str(item.get("import_method") or "") in {"renpy_dialogue", "renpy_string"}]
    if not entries:
        raise RenPyPatchError("package has no Ren'Py patchable entries")
    root = Path(game_root).resolve(); output = Path(output_dir).resolve()
    if root == output or root in output.parents:
        raise RenPyPatchError("Ren'Py patch output must be outside the original game")
    review = load_review_only_keys(Path(csv_path).parent)
    excluded_review_only = 0
    eligible_entries: list[dict] = []
    for entry in entries:
        key = str(entry.get("key") or "")
        if bool(entry.get("review_only")) or key in review:
            excluded_review_only += 1
            continue
        eligible_entries.append(entry)
    entries = eligible_entries
    if not entries:
        raise RenPyPatchError("package has no eligible Ren'Py patchable entries")
    dialogues: list[tuple[dict, str]] = []
    requested_strings: dict[tuple[str, str], str] = {}
    native_ids: set[str] = set()
    source_snapshots: dict[Path, str] = {}
    source_cache: dict[Path, str] = {}
    for entry in entries:
        key = str(entry.get("key") or "")
        row = rows.get(key)
        if not isinstance(row, dict):
            raise RenPyPatchError(f"Ren'Py translation row is missing: {key}")
        translation = str(row.get("translation") or "")
        if patch_skip_reason(entry, translation, set()):
            raise RenPyPatchError(f"Ren'Py entry is not eligible: {key}")
        locator = entry.get("locator") if isinstance(entry.get("locator"), dict) else {}
        contract_reason = validate_renpy_contract(entry)
        if contract_reason:
            raise RenPyPatchError(f"Ren'Py native contract blocked: {contract_reason}")
        source_path = (root / str(entry.get("file_path") or "")).resolve()
        try:
            source_path.relative_to(root)
        except ValueError as exc:
            raise RenPyPatchError("Ren'Py locator escapes game root") from exc
        source_text = str(entry.get("source_text") or "")
        if not source_path.is_file():
            raise RenPyPatchError(f"Ren'Py source precondition drift: {entry.get('file_path')}")
        if source_path not in source_cache:
            try:
                source_cache[source_path] = source_path.read_text(encoding="utf-8")
                source_snapshots[source_path] = _sha256(source_path)
            except (OSError, UnicodeError) as exc:
                raise RenPyPatchError(
                    f"Ren'Py source precondition drift: {entry.get('file_path')}"
                ) from exc
        script = source_cache[source_path]
        source_sha256 = source_snapshots[source_path]
        if source_sha256 != entry["native_contract"]["precondition"]["source_sha256"]:
            raise RenPyPatchError(f"Ren'Py source precondition drift: {entry.get('file_path')}")
        if not _source_present(script, source_text):
            raise RenPyPatchError(f"Ren'Py source precondition drift: {entry.get('file_path')}")
        method = str(entry.get("import_method"))
        if method == "renpy_dialogue":
            native_id = str(locator.get("native_id") or "")
            if native_id in native_ids:
                raise RenPyPatchError(f"duplicate native Ren'Py dialogue identifier: {native_id}")
            native_ids.add(native_id)
            dialogues.append((entry, translation))
        else:
            source = str(locator.get("source") or "")
            contract = entry.get("native_contract") if isinstance(entry.get("native_contract"), dict) else {}
            identity = contract.get("identity") if isinstance(contract.get("identity"), dict) else {}
            language = str(identity.get("language") or "vietnamese")
            if language != "vietnamese":
                raise RenPyPatchError(f"unsupported Ren'Py overlay language: {language}")
            string_identity = (language, source)
            prior = requested_strings.get(string_identity)
            if prior is not None and prior != translation:
                raise RenPyPatchError(f"conflicting Ren'Py string translations for {source!r}")
            requested_strings[string_identity] = translation
    existing_strings, existing_snapshots = _inventory_target_language_mappings(root, "vietnamese")
    _verify_existing_snapshots(existing_snapshots)
    strings: dict[tuple[str, str], str] = {}
    already_satisfied: dict[tuple[str, str], dict[str, object]] = {}
    for identity, translation in requested_strings.items():
        existing = existing_strings.get(identity)
        if existing is None:
            strings[identity] = translation
            continue
        if existing["translation"] != translation:
            raise RenPyPatchError(
                "Ren'Py string mapping conflict for "
                f"({identity[0]!r}, {identity[1]!r}): existing mapping at {existing['path']}:{existing['new_line']} differs"
            )
        already_satisfied[identity] = existing
    target = output / "COPY_TO_GAME_ROOT" / "game" / "tl" / "vietnamese" / "vntext.rpy"
    activation = output / "COPY_TO_GAME_ROOT" / "game" / "zzz_vntext_vietnamese.rpy"
    if target == root or root in target.parents or activation == root or root in activation.parents:
        raise RenPyPatchError("Ren'Py patch output must be outside the original game")
    _validate_overlay_pair(target, activation)
    try:
        payload = _render_overlay(dialogues, strings)
    except RenPyPatchError:
        raise
    except Exception as exc:  # noqa: BLE001 - fail closed at the patch boundary.
        raise RenPyPatchError(f"Ren'Py overlay generation failed: {exc}") from exc
    try:
        activation_payload = _render_activation()
    except RenPyPatchError:
        raise
    except Exception as exc:  # noqa: BLE001 - fail closed at the patch boundary.
        raise RenPyPatchError(f"Ren'Py activation generation failed: {exc}") from exc
    verification_entries, verification_records = _build_verification_records(
        entries,
        dialogues,
        target,
        already_satisfied,
    )
    try:
        _publish_overlay_pair(
            output,
            target,
            activation,
            payload,
            activation_payload,
            existing_snapshots,
            source_snapshots,
        )
    except RenPyPatchError as exc:
        try:
            output.mkdir(parents=True, exist_ok=True)
            verification = _write_verification(
                output,
                target,
                verification_entries,
                False,
                str(exc),
                records=verification_records,
                already_satisfied=len(already_satisfied),
            )
            verification["review_only_skipped"] = excluded_review_only
            (output / "patch_verification.json").write_text(
                json.dumps(verification, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
        except OSError:
            pass
        raise
    report = [
        "patched_lines: " + str(len(dialogues) + len(strings)),
        "already_satisfied: " + str(len(already_satisfied)),
        "review_only_skipped: " + str(excluded_review_only),
        "RENPY native overlay written",
    ]
    (output / "import_report.txt").write_text("\n".join(report) + "\n", encoding="utf-8")
    verification = _write_verification(
        output,
        target,
        verification_entries,
        True,
        records=verification_records,
        already_satisfied=len(already_satisfied),
    )
    verification["review_only_skipped"] = excluded_review_only
    (output / "patch_verification.json").write_text(
        json.dumps(verification, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return report
