# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

ROOT = Path(SPECPATH).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from release.pyinstaller_qt_prune import prune_analysis

ICON = ROOT / "release" / "assets" / "vntext_studio.ico"
VERSION = ROOT / "release" / "version_info.txt"
RELEASE_DEFAULTS = ROOT / "release" / "app_release_defaults.json"
HOOKS = ROOT / "release" / "hooks"

# Optional heavyweight packages not used by the Python preview executable.
EXCLUDED_MODULES = [
    "torch",
    "torchvision",
    "torchaudio",
    "stanza",
    "spacy",
    "thinc",
    "blis",
    "catalogue",
    "cymem",
    "preshed",
    "murmurhash",
    "srsly",
    "wasabi",
    "sympy",
    "matplotlib",
    "pytest",
    "unittest",
    "IPython",
    "jupyter",
    "notebook",
    "transformers",
    "tensorflow",
    "sklearn",
    "scipy",
    "pandas",
    "h5py",
    "onnxruntime.transformers",
    "torch.testing",
    "torch.distributed",
    "torch._inductor",
    "torch._dynamo",
    "torch._vendor",
    "joblib",
    "cloudpathlib",
    "httpx",
    "anyio",
    "typer",
    "rich",
    "pydantic",
    "smart_open",
    "emoji",
    "sacremoses.tests",
    "spacy.tests",
    "stanza.tests",
    "thinc.tests",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebChannel",
    "PySide6.QtWebSockets",
    "PySide6.QtWebView",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DRender",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DExtras",
    "PySide6.QtCharts",
    "PySide6.QtGraphs",
    "PySide6.QtGraphsWidgets",
    "PySide6.QtDataVisualization",
    "PySide6.QtLocation",
    "PySide6.QtPositioning",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtQuick3D",
    "PySide6.QtQuickControls2",
    "PySide6.QtBluetooth",
    "PySide6.QtNfc",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtSensors",
    "PySide6.QtSerialPort",
    "PySide6.QtSerialBus",
    "PySide6.QtTextToSpeech",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtUiTools",
    "PySide6.QtAxContainer",
    "PySide6.QtHttpServer",
    "PySide6.QtStateMachine",
    "PySide6.QtSpatialAudio",
]

block_cipher = None

a = Analysis(
    [str(ROOT / "app.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(RELEASE_DEFAULTS), "vntext"),
        (str(ROOT / "qml_ui" / "qml"), "qml_ui/qml"),
        (str(ROOT / "qml_ui" / "icons"), "qml_ui/icons"),
    ],
    hiddenimports=[
        "ctranslate2",
        "onnxruntime",
        "sentencepiece",
        "sacremoses",
        "UnityPy",
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "PySide6.QtQuick",
        "qml_ui.bridge",
        "qml_ui.app_backend",
        "vntext.qt_app",
        "vntext.qt_workers",
        "vntext.qt_theme",
        "vntext.app_tasks",
        "vntext.app_workflow",
        "tkinter",
        "tkinter.ttk",
        "tkinter.filedialog",
        "tkinter.messagebox",
        "vntext.runtime_paths",
        "vntext.app_update",
        "vntext.app_config",
    ],
    hookspath=[str(HOOKS)],
    hooksconfig={},
    excludes=EXCLUDED_MODULES,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

_pruned_bins, _pruned_datas = prune_analysis(a)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="VNText Studio",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ICON) if ICON.is_file() else None,
    version=str(VERSION) if VERSION.is_file() else None,
)
